import { StyleSheet } from "react-native";
//import Constants from "expo-constants";

export default StyleSheet.create({
  container: {
    //paddingTop: Constants.statusBarHeight,
    paddingBottom: 100,
    borderStyle: "solid",
  },
  titulo: {
    textAlign: "center",
    fontSize: 25,
    fontWeight: "bold",
    color: "#044C8C",
  },
  textoOpcao: {
    fontSize: 15,
    fontWeight: "bold",
    color: "#044C8C",
    paddingLeft: 15,
  },
  containerTitulo: {
    flexDirection: "row",
    alignItems: "center",
    paddingLeft: 15,
    borderBottomColor: "#ccc",
    borderBottomWidth: 1,
    borderStyle: "solid",
    paddingBottom: 20,
  },
  bookContainer: {
    borderWidth: 1,
    borderColor: "#FD5F00",
    paddingLeft: 25,
    paddingRight: 25,
    paddingTop: 15,
    paddingBottom: 15,
    margin: 6,
    borderRadius: 8,
  },
  boxCabecalhoMensagem: {
    flexDirection: "row",
    alignItems: "baseline",
  },
  mensagemDisponivel: {
    textAlign: "center",
    textAlignVertical: "center",
    color: "white",
    borderStyle: "solid",
    borderWidth: 1,
    borderColor: "gray",
    padding: 5,
    backgroundColor: "green",
    width: 40,
    height: 40,
    borderRadius: 50,
  },
  mensagemIndisponivel: {
    textAlign: "center",
    color: "white",
    borderStyle: "solid",
    borderWidth: 1,
    borderColor: "gray",
    borderRadius: 8,
    padding: 5,
    backgroundColor: "gray",
  },
  boxDisponibilidade: {
    borderStyle: "solid",
    borderColor: "lightgreen",
    marginLeft: 10,
  },
  textoDestaque: {
    fontSize: 15,
    fontWeight: "bold",
    color: "#044C8C",
  },
  textoNome: {
    fontSize: 18,
    color: "#044C8C",
  },
  searchContainer: {
    paddingTop: 15,
    flexDirection: "row",
    paddingBottom: 20,
  },
  searchItem: {
    borderWidth: 1,
    borderColor: "#044C8C",
    padding: 5,
    margin: 6,
    width: "75%",
    borderRadius: 8,
  },
  searchItemInput: {
    textAlign: "center",
    fontSize: 14,
    color: "#044C8C",
  },
  searchContainerItem: {
    alignItems: "center",
    alignSelf: "center",
  },
  items: {
    marginTop: 5,
    width: "100%",
    height: 45,
    borderRadius: 8,
    borderColor: "#FD5F00",
    borderWidth: 2,
    paddingLeft: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  textoBotao: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#044C8C",
  },
});
